function KPIplots()

% TITLES FOR FIGURES
titles = { ...
    'I=0.0', ...              
    'I=0.5', ...                
    'I=1.0', ...              
    'I=2.0', ...                
    'I=3.0', ...          
    'I=4.0', ...              
    'I=5.0', ...                
    'I=6.0', ...
    'I=7.0', ...              
    'I=8.0', ...                
    'I=9.0', ...
    'I=10.0'
    };
% NAMES OF SCENARIOS
scenarios = { ...
       'scenBaseR_MVD'
    };
%% Compute TTS and num inc table

itau = 'tau=00';

for ri = 1: numel(titles)
        
        fname = sprintf('%s_%s_%s.mat',scenarios{1}, titles{ri}, itau);
        load(fname,'Sim');
        
          %save the data in fields
          tbl(ri,1) = Sim.Edie.TTS;
%         mineKPI = setfield(mineKPI, fname, 'speed', {iscenario}, Sim.Edie.u);
%         mineKPI = setfield(mineKPI, fname, 'TTS'  , {iscenario}, Sim.Edie.TTS);
%         mineKPI = setfield(mineKPI, fname, 'NoA'  , {iscenario}, Sim.numCollisions);
end


%% Create Figures
disp('TTS KPI ...');
figttskpi = figure; %figtraj.WindowStyle = 'docked'; 
figttskpi.Name = sprintf('TTS KPI');
figttskpi.Position = [50,50,1536,768];
cla; axSim = gca;
for i = 1:numel(titles)
    atitle = titles(i);
    %bTaustr = sprintf('tau%.2d',taus(i));
    subplot(3,4,i);
    spider_plot_R2019b(getfield(mineKPI,bTaustr,'TTS'),...
    'AxesLabels', titles,...
    'AxesInterval', 4,...
    'AxesDisplay', 'one',...
    'AxesFont', 'Times New Roman',...
    'LabelFont', 'Times New Roman',...
    'AxesFontSize', 12,...
    'LabelFontSize', 10,...
    'LineStyle', {'--'},...
    'LineWidth', [1],...
    'Marker', {'o'},...
    'MarkerSize', [8],...
    'FillOption', 'on',...
    'FillTransparency', 0.2,...
    'Color', [1, 0, 0]...
    );
    title(atitle);

end

saveas(figttskpi  ,'TTSKPI.png');

disp('FLOW KPI ...');
figflowkpi = figure; %figtraj.WindowStyle = 'docked'; 
figflowkpi.Name = sprintf('FLOW KPI');
figflowkpi.Position = [50,50,1536,768];
cla; axSim = gca;
for i = 1:numel(taus)
    aTaustr = sprintf('tau=%.2d',taus(i));
    bTaustr = sprintf('tau%.2d',taus(i));
    subplot(2,3,i);
    spider_plot_R2019b(getfield(mineKPI,bTaustr,'flow'),...
    'AxesLabels', titles,...
    'AxesInterval', 2,...
    'AxesDisplay', 'one',...
    'AxesFont', 'Times New Roman',...
    'LabelFont', 'Times New Roman',...
    'AxesFontSize', 12,...
    'LabelFontSize', 10,...
    'LineStyle', {'--'},...
    'LineWidth', [1],...
    'Marker', {'o'},...
    'MarkerSize', [8],...
    'FillOption', 'on',...
    'FillTransparency', 0.2,...
    'Color', [0, 1, 0]...
    );
    title(aTaustr);
end
saveas(figflowkpi  ,'FLOWKPI.png');

disp('SPEED KPI ...');
figspeedkpi = figure; %figtraj.WindowStyle = 'docked'; 
figspeedkpi.Name = sprintf('SPEED KPI');
figspeedkpi.Position = [50,50,1536,768];
cla; axSim = gca;
for i = 1:numel(taus)
    aTaustr = sprintf('tau=%.2d',taus(i));
    bTaustr = sprintf('tau%.2d',taus(i));
    subplot(2,3,i);
    spider_plot_R2019b(getfield(mineKPI,bTaustr,'speed'),...
    'AxesLabels', titles,...
    'AxesInterval', 2,...
    'AxesDisplay', 'one',...
    'AxesFont', 'Times New Roman',...
    'LabelFont', 'Times New Roman',...
    'AxesFontSize', 12,...
    'LabelFontSize', 10,...
    'LineStyle', {'--'},...
    'LineWidth', [1],...
    'Marker', {'o'},...
    'MarkerSize', [8],...
    'FillOption', 'on',...
    'FillTransparency', 0.2,...
    'Color', [0, 0, 1]...
    );
    title(aTaustr);
end

saveas(figspeedkpi  ,'SPEEDKPI.png');

disp('NUMBER OF ACCIDENTS KPI ...');
fignoakpi = figure; %figtraj.WindowStyle = 'docked'; 
fignoakpi.Name = sprintf('ACCIDENTS KPI');
fignoakpi.Position = [50,50,1536,768];
cla; axSim = gca;
for i = 1:numel(taus)
 aTaustr = sprintf('tau=%.2d',taus(i));
    bTaustr = sprintf('tau%.2d',taus(i));
    subplot(2,3,i);
    minaxes = min(getfield(mineKPI,bTaustr,'NoA'));
    maxaxes = max(getfield(mineKPI,bTaustr,'NoA'));
    if maxaxes == 0
        maxaxes = 1;
        matmax(1:length(getfield(mineKPI,bTaustr,'NoA'))) = maxaxes;
    else
        matmax(1:length(getfield(mineKPI,bTaustr,'NoA'))) = maxaxes;
    end
    
    matmin(1:length(getfield(mineKPI,bTaustr,'NoA'))) = minaxes;
    
    spider_plot_R2019b(getfield(mineKPI,bTaustr,'NoA'),...
    'AxesLimits',[matmin;matmax],...
    'AxesLabels', titles,...
    'AxesInterval', 2,...
    'AxesDisplay', 'one',...
    'AxesFont', 'Times New Roman',...
    'LabelFont', 'Times New Roman',...
    'AxesFontSize', 12,...
    'LabelFontSize', 10,...
    'LineStyle', {'--'},...
    'LineWidth', [1],...
    'Marker', {'o'},...
    'MarkerSize', [8],...
    'FillOption', 'on',...
    'FillTransparency', 0.2,...
    'Color', [1, 1, 0]...
    );
    title(aTaustr);
end
saveas(fignoakpi  ,'NoAKPI.png');
end